In [37]:
import numpy as np
from scipy.special import softmax

In [38]:
def generate_data(data):
    X = data[:, :-1]
    # one = np.ones((X.shape[0], 1))
    # X= np.hstack((one,X))
    X= X.astype(np.float64)
    Y = data[:, -1]
    Y = Y.astype(int)-1
    unique, counts = np.unique(Y, return_counts=True)
    W =np.zeros((X.shape[1]+1, len(unique)), dtype=np.float64)
    return X,Y,W,counts

def g(W,x,j):
    z = np.dot(x,W)
    sm= softmax(z)
    return sm[j]

def loss(X,Y,W,counts):
    n = X.shape[0]
    Z = X @ W
    softmax_probs = softmax(Z, axis=1)
    indices = (np.arange(n), Y)
    correct_class_probs = softmax_probs[indices]
    scaled_probs = np.log(correct_class_probs) / counts[Y]
    loss_value = -np.mean(scaled_probs) / 2
    return loss_value

def compute_gradient(X, Y, W, counts):
    n, m = X.shape
    k = W.shape[1]
    z = X @ W  
    softmax_probs = softmax(z, axis=1) 
    indices = (np.arange(n), Y)
    Y_one_hot = np.zeros((n, k))
    Y_one_hot[indices] = 1
    grad_W = X.T @ ((softmax_probs - Y_one_hot) / counts[Y][:, np.newaxis]) / (2 * n) 
    return grad_W

In [39]:
# def compute_n_partb(X, Y, W, gradient, n0, counts):
#     nl = 0.0
#     nh = n0
#     while loss(X, Y, W, counts) > loss(X, Y, W - nh*gradient, counts):
#         nh *= 2
#     while loss(X, Y, W, counts) < loss(X, Y, W - nh*gradient, counts):
#         nh /= 2
#     nh *= 2
#     for _ in range(20):
#         n1 = (2*nl + nh)/3
#         n2 = (nl + 2*nh)/3
#         if loss(X, Y, W - n1*gradient, counts) > loss(X, Y, W - n2*gradient, counts):
#             nl = n1
#         else:
#             nh = n2
#     return nh-nl,(nl+nh)/2

# import matplotlib.pyplot as plt
# import numpy as np

# def compute_n_partb(X, Y, W, gradient, n0, counts):
#     nl = 0.0
#     nh = n0

#     # Arrays to store n values and corresponding loss values
#     n_values = []
#     loss_values = []

#     # Store the initial loss for W
#     initial_loss = loss(X, Y, W, counts)

#     # Find the upper bound for n (nh)
#     while loss(X, Y, W, counts) > loss(X, Y, W - nh * gradient, counts):
#         nh *= 2
#         n_values.append(nh)
#         loss_values.append(loss(X, Y, W - nh * gradient, counts))

#     # Find the correct nh value
#     while loss(X, Y, W, counts) < loss(X, Y, W - nh * gradient, counts):
#         nh /= 2
#         n_values.append(nh)
#         loss_values.append(loss(X, Y, W - nh * gradient, counts))

#     nh *= 2
#     n_values.append(nh)
#     loss_values.append(loss(X, Y, W - nh * gradient, counts))

#     # Use ternary search to refine nl and nh
#     for _ in range(5):
#         n1 = (2 * nl + nh) / 3
#         n2 = (nl + 2 * nh) / 3

#         loss_n1 = loss(X, Y, W - n1 * gradient, counts)
#         loss_n2 = loss(X, Y, W - n2 * gradient, counts)

#         if loss_n1 > loss_n2:
#             nl = n1
#         else:
#             nh = n2

#         n_values.extend([n1, n2])
#         loss_values.extend([loss_n1, loss_n2])

#     # Finally, append the midpoint loss
#     midpoint = (nl + nh) / 2
#     final_loss = loss(X, Y, W - midpoint * gradient, counts)
#     n_values.append(midpoint)
#     loss_values.append(final_loss)

#     # Plotting n vs Loss with color variation
#     plot_n_vs_loss(n_values, loss_values)

#     return midpoint

# def plot_n_vs_loss(n_values, loss_values):
#     # Normalize the color range based on the index of n_values
#     colors = np.linspace(0, 1, len(n_values))

#     # Create a scatter plot with color variation
#     scatter = plt.scatter(n_values, loss_values, c=colors, cmap='viridis', edgecolor='k')

#     # Plot lines connecting the points
#     plt.plot(n_values, loss_values, color='gray', linestyle='--')

#     # Add color bar to show the mapping of iteration index to color
#     cbar = plt.colorbar(scatter)
#     cbar.set_label('Iteration Index')

#     plt.xlabel("n values")
#     plt.ylabel("Loss values")
#     plt.title("n vs Loss with Color Varying by Iteration Index")
#     plt.show()

# # Usage example: You will need to pass your own X, Y, W, gradient, n0, and counts values
# # compute_n_partb(X, Y, W, gradient, n0, counts)



In [40]:
def compute_n_partb(X, Y, W, gradient, n0, counts):
    nl = 0.0
    nh = n0
    prev_loss= loss(X, Y, W, counts)
    while prev_loss > loss(X, Y, W - nh*gradient, counts):
        prev_loss= loss(X, Y, W - nh*gradient, counts)
        nh *= 2
    if abs(nh-n0)<1e-9:
        while loss(X, Y, W, counts) < loss(X, Y, W - nh*gradient, counts):
            nh /= 2
        nh *= 2
    for _ in range(5):
        n1 = (2*nl + nh)/3
        n2 = (nl + 2*nh)/3
        if loss(X, Y, W - n1*gradient, counts) > loss(X, Y, W - n2*gradient, counts):
            nl = n1
        else:
            nh = n2
    return (nl+nh)/2

In [41]:


def gradient_descent3_partb(X, Y, W, counts, n0, epochs, batch_size):
    n = X.shape[0]
    for _ in range(epochs):
        batch_num = 0
        for start in range(0, n, batch_size):
            end = min(start + batch_size, n)
            X_batch = X[start:end]
            Y_batch = Y[start:end]
            batch_loss = loss(X_batch, Y_batch, W, counts)
            print(f"Epoch{_+1}, Batch{1+int(start/batch_size)}, Loss{batch_loss}")

            gradient = compute_gradient(X_batch, Y_batch, W, counts)
            learning_rate= compute_n_partb(X_batch, Y_batch, W, gradient, n0, counts)
            W -= learning_rate * gradient
            batch_num += 1
    return W

In [42]:
from sklearn.preprocessing import StandardScaler
train = np.loadtxt("Assignment1.2/train1.csv", delimiter=",", skiprows=1)
test = np.loadtxt("Assignment1.2/test1.csv", delimiter=",", skiprows=1)
actual_pred = np.loadtxt("Assignment1.2/test_pred1.csv", delimiter=",", skiprows=1)
X,Y,W,counts = generate_data(train)
X_test = test
one = np.ones((X_test.shape[0], 1))
X_test= X_test.astype(np.float64)
print(X.shape)
scaler = StandardScaler().fit(X)
X = scaler.transform(X)
X_test = scaler.transform(X_test)
X_test= np.hstack((one,X_test))
one = np.ones((X.shape[0],1))
X= np.hstack((one,X))

(87595, 1183)


In [43]:
W= gradient_descent3_partb(X,Y,W,counts,1e4,25,87595)

Epoch1, Batch1, Loss3.165236283166598e-05
Epoch2, Batch1, Loss2.475439726503823e-05
Epoch3, Batch1, Loss2.291654817775092e-05
Epoch4, Batch1, Loss2.2246727351364132e-05
Epoch5, Batch1, Loss2.1830604666013927e-05
Epoch6, Batch1, Loss2.1558488174050303e-05
Epoch7, Batch1, Loss2.1353997701490082e-05
Epoch8, Batch1, Loss2.119708134274187e-05
Epoch9, Batch1, Loss2.1069220925874506e-05
Epoch10, Batch1, Loss2.096638970421969e-05
Epoch11, Batch1, Loss2.0883063529037526e-05
Epoch12, Batch1, Loss2.081534180330254e-05
Epoch13, Batch1, Loss2.0757484251740366e-05
Epoch14, Batch1, Loss2.07074253472993e-05
Epoch15, Batch1, Loss2.0663017208185433e-05
Epoch16, Batch1, Loss2.0622706020865116e-05
Epoch17, Batch1, Loss2.0586200475372847e-05
Epoch18, Batch1, Loss2.055203396093484e-05
Epoch19, Batch1, Loss2.0522096411227737e-05
Epoch20, Batch1, Loss2.049365613490433e-05
Epoch21, Batch1, Loss2.0468709358615234e-05
Epoch22, Batch1, Loss2.0444087976811308e-05
Epoch23, Batch1, Loss2.042031652875496e-05
Epoch24,

In [44]:
print(W.shape)
print(W[:5])

(1184, 4)
[[ 0.02385923 -0.50396173  0.12265108  0.35745141]
 [-0.04375223  0.00505362 -0.01048819  0.0491868 ]
 [-0.03077164  0.05612169 -0.05248986  0.02713981]
 [-0.00302366 -0.00132851  0.00153493  0.00281723]
 [ 0.0300145  -0.06872048  0.01564375  0.02306223]]


In [45]:
Z = X_test @ W
softmax_probs = softmax(Z, axis=1)
print(Z[:5])
output_model_pred = np.argmax(Z, axis=1) + 1

[[-0.129259    0.12518396 -0.80655386  0.8106289 ]
 [-0.62405338  0.54188117  1.41891549 -1.33674328]
 [ 0.85573476 -1.22864679 -0.9545532   1.32746523]
 [ 0.82579188 -1.47940801  0.2755804   0.37803573]
 [-0.84518132 -0.80887482  2.13409953 -0.48004338]]


In [46]:
# write the softmax_probs in a csv file, with each row as comma separated value as probability of each class
np.savetxt("modelpredictionsb.csv", softmax_probs, delimiter=",")
np.savetxt("temp.csv", output_model_pred, delimiter=",")

In [47]:
actual_pred= actual_pred.astype(int)-1
test_unique, test_counts= np.unique(actual_pred, return_counts=True)
print(loss(X_test, actual_pred, W, test_counts))
    

3.521534578755681e-05


In [48]:
print(counts)

[16131  1032 25406 45026]
